config/routes.rb
Kungfu::Application.routes.draw do
  resources :directors

  resources :studios

  resources :films do
    collection do
      get :search
    end
  end

  root :to => 'films#index'
  get '/my', :to => 'films#my'
  get "/year/:year" => "films#year"

end

app/models/director.rb
class Director < ActiveRecord::Base
	attr_accessible :name
	has_many :films
end

app/models/film.rb
class Film < ActiveRecord::Base
  attr_accessible :director_id, :notes, :rating, :studio_id, :title, :year, :watched, :youtube, :dvd, :bluray, :drive, :streaming, :buy
  belongs_to :studio
  belongs_to :director
end

app/models/studio.rb
class Studio < ActiveRecord::Base
  attr_accessible :name
  has_many :films
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @directors }
    end
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
    @director = Director.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @director }
    end
  end

  # GET /directors/new
  # GET /directors/new.json
  def new
    @director = Director.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @director }
    end
  end

  # GET /directors/1/edit
  def edit
    @director = Director.find(params[:id])
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(params[:director])

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render json: @director, status: :created, location: @director }
      else
        format.html { render action: "new" }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /directors/1
  # PUT /directors/1.json
  def update
    @director = Director.find(params[:id])

    respond_to do |format|
      if @director.update_attributes(params[:director])
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director = Director.find(params[:id])
    @director.destroy

    respond_to do |format|
      format.html { redirect_to directors_url }
      format.json { head :no_content }
    end

  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  # GET /films
  # GET /films.json
  def index
    require 'open-uri'
    require 'json'
    @films = Film.order(:year)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @films }
    end
  end

  def my
    require 'open-uri'
    require 'json'
    @films = Film.order(:year)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @films }
    end
  end

  # GET /films/1
  # GET /films/1.json
  def show
    @film = Film.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @film }
    end
  end

  def year
    @film = Film.find(params[:year])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @film }
    end
  end


  # GET /films/new
  # GET /films/new.json
  def new
    @film = Film.new

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @film }
    #   format.js
    # end
  end

  # GET /films/1/edit
  def edit
    @film = Film.find(params[:id])
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(params[:film])
    respond_to do |format|
      @film.save
      format.html { redirect_to  my_path, notice: 'Film was successfully created.' }
      format.json { render json: @film, status: :created, location: @film }
      format.js
    end
  end

  # PUT /films/1
  # PUT /films/1.json
  def update
    @film = Film.find(params[:id])
    @film.update_attributes(params[:film])
    respond_to do |format|
        format.html { redirect_to  my_path, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
        format.js
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film = Film.find(params[:id])
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  # GET /studios
  # GET /studios.json
  def index
    @studios = Studio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @studios }
    end
  end

  # GET /studios/1
  # GET /studios/1.json
  def show
    @studio = Studio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @studio }
    end
  end

  # GET /studios/new
  # GET /studios/new.json
  def new
    @studio = Studio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @studio }
    end
  end

  # GET /studios/1/edit
  def edit
    @studio = Studio.find(params[:id])
  end

  # POST /studios
  # POST /studios.json
  def create
    @studio = Studio.new(params[:studio])

    respond_to do |format|
      if @studio.save
        format.html { redirect_to @studio, notice: 'Studio was successfully created.' }
        format.json { render json: @studio, status: :created, location: @studio }
      else
        format.html { render action: "new" }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /studios/1
  # PUT /studios/1.json
  def update
    @studio = Studio.find(params[:id])

    respond_to do |format|
      if @studio.update_attributes(params[:studio])
        format.html { redirect_to @studio, notice: 'Studio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studios/1
  # DELETE /studios/1.json
  def destroy
    @studio = Studio.find(params[:id])
    @studio.destroy

    respond_to do |format|
      format.html { redirect_to studios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/directors/_form.html.erb
<%= simple_form_for(@director) do |f| %>
  <% if @director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% @director.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<h1>Editing director</h1>

<%= render 'form' %>

<%= link_to 'Show', @director %> |
<%= link_to 'Back', directors_path %>

app/views/directors/index.html.erb
<h1>Listing directors</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @directors.each do |director| %>
  <tr>
    <td><%= director.name %></td>
    <td><%= link_to 'Show', director %></td>
    <td><%= link_to 'Edit', edit_director_path(director) %></td>
    <td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Director', new_director_path %>

app/views/directors/new.html.erb
<div class="edit-contain">
	<h1>New director</h1>
	<%= render 'form' %>
</div>
<%= link_to 'Back', directors_path %>

app/views/directors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @director.name %>
</p>


<%= link_to 'Edit', edit_director_path(@director) %> |
<%= link_to 'Back', directors_path %>

app/views/films/_film.html.erb
 <tr class="<%= cycle('even', 'odd') -%>" id="film_<%= film.id %>">
    <td class="film-year"><%= film.year.year %></td>
    <td class="film-title"><%= film.title %></td>
    <td><% (1..10).each do |n| %>
            <% if n==film.rating %>
                <input name="star<%= film.id %>" type="radio" class="star" disabled="disabled" checked="checked"/>
            <% else %>
                <input name="star<%= film.id %>" type="radio" class="star" disabled="disabled"/>
            <% end %>
        <% end %>
    </td>
    <td>
         <% if film.buy %>
          <a target="_blank" href="<%= film.buy %>"><i class="icon-basket"></i></a>
        <% end %>
    </td>
    <td>
         <% if film.bluray %>
            <i class="watch-icon icon-cd bluray-icon"></i>
        <% end %>
        <% if film.dvd %>
            <i class="watch-icon icon-cd dvd-icon"></i>
        <% end %>
        <% if film.drive %>
            <i class="watch-icon icon-hdd drive-icon"></i>
        <% end %>
        <% if film.youtube != "" and film.youtube  %>
            <a class="youtube-icon fancybox-media" href="<%= film.youtube %>"><i class="watch-icon icon-youtube"></i></a>
        <% end %>
    </td>
    <td class="modify">
        <%= link_to(edit_film_path(film)) do %><i class="icon-pencil"></i><% end %>
        <%= link_to(film, method: :delete, remote: true) do %><i class="icon-cancel-circle"></i><% end %>
    </td>
  </tr>

app/views/films/_form.html.erb
<%= simple_form_for @film, remote: true do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>
      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :title %>
    <%= f.input :year, :start_year => 1960  %>
    <%= f.input :studio_id, :collection => Studio.all, :selected => :id  %>
    <%= f.input :watched %>
    <%= f.input :bluray %>
    <%= f.input :dvd %>
    <%= f.input :drive %>
    <%= f.input :youtube %>
    <%= f.input :streaming %>
    <%= f.input :buy %>

  <div class="rating-form form">
    <%= f.label :rating %><br />
    <%= f.radio_button(:rating, 1,  class: "star") %>
    <%= f.radio_button(:rating, 2,  class: "star") %>
    <%= f.radio_button(:rating, 3,  class: "star") %>
    <%= f.radio_button(:rating, 4,  class: "star") %>
    <%= f.radio_button(:rating, 5,  class: "star") %>
    <%= f.radio_button(:rating, 6,  class: "star") %>
    <%= f.radio_button(:rating, 7,  class: "star") %>
    <%= f.radio_button(:rating, 8,  class: "star") %>
    <%= f.radio_button(:rating, 9,  class: "star") %>
    <%= f.radio_button(:rating, 10,  class: "star") %>
    <br />
  </div>
  <%= f.input :director_id, :collection => Director.all, :selected => :id  %>
  <%= f.input :notes %>
  <div class="actions">
    <%= f.submit  'Submit', :class => 'btn btn-primary btn-large' %>
  </div>
<% end %>

app/views/films/_tform.html.erb
<%= simple_form_for @film, remote: true do |f| %>
<h3>Edit FIlm</h3>
    <div colspan="10"><%= f.input :year, :start_year => 1960  %>
    <%= f.input :title %>
    <%= f.radio_button(:rating, 1,  class: "star") %>
    <%= f.radio_button(:rating, 2,  class: "star") %>
    <%= f.radio_button(:rating, 3,  class: "star") %>
    <%= f.radio_button(:rating, 4,  class: "star") %>
    <%= f.radio_button(:rating, 5,  class: "star") %>
    <%= f.radio_button(:rating, 6,  class: "star") %>
    <%= f.radio_button(:rating, 7,  class: "star") %>
    <%= f.radio_button(:rating, 8,  class: "star") %>
    <%= f.radio_button(:rating, 9,  class: "star") %>
    <%= f.radio_button(:rating, 10,  class: "star") %>
    <%= f.input :studio_id, :collection => Studio.all, :selected => @film.studio_id  %>
    <%= f.input :director_id, :collection => Director.all, :selected => @film.director_id  %>
    <%= f.input :watched %>
    <%= f.input :bluray %>
    <%= f.input :dvd %>
    <%= f.input :drive %>
    <%= f.input :youtube %>
    <%= f.input :streaming %>
    <%= f.input :buy %>
      <%= f.input :notes %>
      <%= f.submit  'Submit', :class => 'btn btn-primary btn-large' %>
        </div>
<% end %>

app/views/films/create.js.erb
$('#new_film').slideUp();
$('#new_film_btn').fadeIn();
$('.films-table tbody').append('<%= j render(@film) %>')

app/views/films/destroy.js.erb
$('#<%= dom_id(@film) %>').fadeOut();

app/views/films/edit.html.erb
<div class="edit-contain">
	<h1>Editing film</h1>
	<%= render 'tform' %>
</div>
<%= link_to 'Show', @film %> |
<%= link_to 'Back', my_path %>

app/views/films/edit.js.erb
$('.page').after('<%= j render("tform") %>');
$('.edit_film').hide().fadeIn();

app/views/films/index.html.erb
<table class="films-table">
    <thead>
        <tr>
          <th>Year</th>
          <th>Title</th>
          <th>Director</th>
          <th>Studio</th>
          <th>Rating</th>
          <th>Buy</th>
          <th>Watch</th>
        </tr>
    </thead>
    <tbody>
<% @films.each do |film| %>
  <tr class="<%= cycle('even', 'odd') -%>">
    <td class="film-year"><%= film.year.year %></td>
    <td class="film-title"><%= film.title %></td>
    <td><%= film.director.name %></td>
     <td><%= film.studio.name %></td>
    <td><% (1..10).each do |n| %>
            <% if n==film.rating %>
                <input name="star<%= film.id %>" type="radio" class="star" disabled="disabled" checked="checked"/>
            <% else %>
                <input name="star<%= film.id %>" type="radio" class="star" disabled="disabled"/>
            <% end %>
        <% end %>
    </td>

    <td>
         <% if film.buy != '' and film.buy %>
          <a target="_blank" href="<%= film.buy %>"><i class="icon-basket"></i></a>
        <% end %>
    </td>
    <td>
        <% if film.youtube != "" and film.youtube  %>
            <a class="youtube-icon fancybox-media" href="<%= film.youtube %>"><i class="watch-icon icon-youtube"></i></a>
        <% end %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

app/views/films/my.html.erb
<div class="links clearfix">
    <%= link_to "Add New Film",  new_film_path, class: 'btn add-btn', id: 'new_film_btn', remote: true %>
</div>
<img src='<%= @poster %>' />
<%= @test %>
<table class="films-table">
    <thead>
        <tr>
          <th>Year</th>
          <th>Title</th>
          <th>Director</th>
          <th>Studio</th>
          <th>Rating</th>
          <th>Buy</th>
          <th>Watch</th>
          <th>Modify</th>
        </tr>
    </thead>
    <tbody>
<% @films.each do |film| %>
  <tr class="<%= cycle('even', 'odd') -%>" id="film_<%= film.id %>">
    <td class="film-year"><%= film.year.year %></td>
    <td class="film-title"><%= film.title %></td>
    <td class="film-director">
      <%= film.director.name %>
    </td>
      <td class="film-studio">
      <%= film.studio.name %>
    </td>
    <td><% (1..10).each do |n| %>
            <% if n==film.rating %>
                <input name="star<%= film.id %>" type="radio" class="star" disabled="disabled" checked="checked"/>
            <% else %>
                <input name="star<%= film.id %>" type="radio" class="star" disabled="disabled"/>
            <% end %>
        <% end %>
    </td>
    <td>
         <% if film.buy != '' and film.buy %>
            <a target="_blank" href="<%= film.buy %>"><i class="icon-basket"></i></a>
        <% end %>
    </td>
    <td>
         <% if film.bluray != '' and film.bluray %>
            <i class="watch-icon icon-cd bluray-icon"></i>
        <% end %>
        <% if film.dvd != ''and film.dvd %>
            <i class="watch-icon icon-cd dvd-icon"></i>
        <% end %>
        <% if film.drive != '' and film.drive %>
            <i class="watch-icon icon-hdd drive-icon"></i>
        <% end %>
        <% if film.youtube != "" and film.youtube  %>
            <a class="youtube-icon fancybox-media" href="<%= film.youtube %>"><i class="watch-icon icon-youtube"></i></a>
        <% end %>
    </td>
    <td class="modify">
        <%= link_to(edit_film_path(film), remote: true) do %><i class="icon-pencil"></i><% end %>
        <%= link_to(film, method: :delete, remote: true) do %><i class="icon-cancel-circle"></i><% end %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

app/views/films/new.html.erb
<div class="edit-contain">
	<h1>New film</h1>
	<%= render 'form' %>
</div>
<%= link_to 'Back', films_path %>

app/views/films/new.js.erb
$("#new_film_btn").fadeOut().after('<%= j render("form") %>');
$("#new_film").hide().slideDown();

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @film.title %>
</p>

<p>
  <b>Year:</b>
  <%= @film.year %>
</p>

<p>
  <b>Studio:</b>
  <%= @film.studio %>
</p>

<p>
  <b>Rating:</b>
  <%= @film.rating %>
</p>

<p>
  <b>Director:</b>
  <%= @film.director %>
</p>

<p>
  <b>Notes:</b>
  <%= @film.notes %>
</p>


<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>

app/views/films/update.js.erb
$('.edit_film').fadeOut().remove();

app/views/layouts/_header.html.erb
<header>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <h1 class="logo"><%= link_to "Kung Fu List ", root_path, class: 'brand' %></h1>
      <div class="nav-collapse collapse">
          </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kungfu</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-9079749-9', 'kungfufilmlist.com');
  ga('send', 'pageview');

</script>
</head>
<body>
	<div class="page">
	<%= render '/layouts/header' %>
		<%= yield %>
	</div>
</body>
</html>

app/views/studios/_form.html.erb
<%= simple_form_for(@studio) do |f| %>
  <% if @studio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@studio.errors.count, "error") %> prohibited this studio from being saved:</h2>

      <ul>
      <% @studio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studios/edit.html.erb
<h1>Editing studio</h1>

<%= render 'form' %>

<%= link_to 'Show', @studio %> |
<%= link_to 'Back', studios_path %>

app/views/studios/index.html.erb
<h1>Listing studios</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @studios.each do |studio| %>
  <tr>
    <td><%= studio.name %></td>
    <td><%= link_to 'Show', studio %></td>
    <td><%= link_to 'Edit', edit_studio_path(studio) %></td>
    <td><%= link_to 'Destroy', studio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Studio', new_studio_path %>

app/views/studios/new.html.erb
<div class="edit-contain">
	<h1>New studio</h1>
	<%= render 'form' %>
</div>
<%= link_to 'Back', studios_path %>

app/views/studios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @studio.name %>
</p>


<%= link_to 'Edit', edit_studio_path(@studio) %> |
<%= link_to 'Back', studios_path %>